##     ## ########       ###    ########  ####
##     ##    ##         ## ##   ##     ##  ##
##     ##    ##        ##   ##  ##     ##  ##
##     ##    ##       ##     ## ########   ##
 ##   ##     ##       ######### ##         ##
  ## ##      ##       ##     ## ##         ##
   ###       ##       ##     ## ##        ####

name: VillagerTradeApi
main: com.gmail.fedmanddev.villagerapi.VillagerTradeApi
version: 1.0.3
author: [Fedmand]
authors: [GitHub/Curspex, Omnivion]
description: Villager trading api
database: false
website: http://cur.sx
dev-url: https://github.com/Curspex/VillagerTradeApi
original: http://dev.bukkit.org/bukkit-plugins/villager-trade-api/